### ISSUE TITLE
Strange artifacts in octree result for tiff slice conversion

### ISSUE THREAD

**Issue by carshadi** [JaneliaSciComp/hortacloud-importer#2]
Hello,

I am getting an odd result when converting a directory of tiff slices, where each slice is named according to z-depth "[0-255].tif"
My volume shape is (256,256,256)

The result has some odd staircase artifacts that are not present in the original volume 

Octree result:
<img width="385" alt="staircase_artifacts" src="https://user-images.githubusercontent.com/44130022/173930019-33d2ad3f-79ed-4029-be75-7cc150263757.png">

Original volume:
<img width="385" alt="expected" src="https://user-images.githubusercontent.com/44130022/173930077-d0eb897a-1d18-4222-9060-a39ec0df872b.png">

command:

```shell
python tiff2octree.py -i "C:\Users\cameron.arshadi\Desktop\block_11" -l 3 -o "C:\Users\cameron.arshadi\Desktop\20210812-AG_block_11" -d 2ndmax -t 4 --ktxonly -c 0 --voxsize="1.1,1.1,1.1"
```

I have tried levels 1-4, all give the same result. Using `area` and `aa` downsampling also makes no difference. 

This occurs with the latest `main` branch cef8fc7f4a08133ca6d470070cbe079f36e482f6, as well as at this point ed9b1a9637d623a5d81d597a54656dd3f590032d 

I posted the volume on google drive in case you are interested https://drive.google.com/drive/folders/1YRxDwMg3t3clROw0KT9xfZQ_AklUrQeX?usp=sharing

Any ideas what the issue could be?

Thank you,
Cameron

**Comment by takashi310** [comment]
I am sorry for my late reply.
The converter is sorting image files in the natural sort order. If your files are named 9.tif; 10.tif; etc., the converter cannot build a stack in the correct order. The slice numbers must be zero-padded (e.g. 009.tif, 010.tif).

**Comment by carshadi** [comment]
Thanks that makes sense
